export const CART_SET_PRODUCT_LIST = "CART/SET_PRODUCT_LIST";
export const CART_SET_LOADING = "CART/SET_LOADING";
export const CART_SET_ERROR = "CART/SET_ERROR";
export const CART_FETCH_PRODUCT_LIST = "CART/FETCH_PRODUCT_LIST";